version: "3.7"
services:
  web:
    build:
      context: "./nginx"
      dockerfile: "nginx-1.19.dockerfile"
    container_name: "app_nginx"
    ports:
      - "8080:80"
    volumes:
      - "./html/public/:/var/www/html/"
      - "./errorpages/:/var/www/errorpages/"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf/"
  php:
    image: "php:7.4.0-fpm-alpine"
    container_name: "app_php"
    volumes:
      - "./html/public/:/var/www/html/"
